services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - absolute_net

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing local/pages;
      mc mb --ignore-existing local/panels;
      mc mb --ignore-existing local/comics;
      mc mb --ignore-existing local/audios;
      mc mb --ignore-existing local/videos;
      mc mb --ignore-existing local/vabs;
      mc anonymous set download local/pages;
      mc anonymous set download local/panels;
      mc anonymous set download local/comics;
      mc anonymous set download local/audios;
      mc anonymous set download local/videos;
      mc anonymous set download local/vabs;
      echo 'Buckets created and set to public.';
      "
    networks:
      - absolute_net

  amq:
    image: rabbitmq:3-management-alpine
    container_name: amq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - amq_data:/var/lib/rabbitmq/
      - amq_data:/var/log/rabbitmq
    networks:
      - absolute_net


volumes:
  minio_data:
  amq_data:

networks:
  absolute_net:
    driver: bridge
